services:
  postgres:
    image: postgres:17
    container_name: finance-db
    environment:
      POSTGRES_DB: finance-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "gelhu@1234"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: finance-tracker
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/finance-db"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "gelhu@1234"

volumes:
  postgres_data:

